# Generated by Django 3.0.8 on 2020-08-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('group', models.CharField(choices=[('notebook', 'notebook'), ('accessories', 'accessories'), ('pc', 'pc'), ('mobile', 'mobile')], default='mobile', max_length=20)),
                ('img', models.ImageField(default='no-image.jpg', upload_to='product_image')),
            ],
        ),
    ]
